export const USER_ROLES = {
    CUSTOMER:"CUSTOMER",
    OWNER:"OWNER",
    MANAGER:"MANAGER"
}

export const SHOP_TYPES = {
    STALL:"STALL",
    RESTAURANT:"RESTAURANT"
}

export const APP_LANGUAGE = {
    EN:'en',
    HI:'hi'
}

export const MENU_CATEGORY_GROUP_TYPE = {
    DIETARY_BASED: "DIETARY_BASED",
    SPICE_LEVEL_BASED: "SPICE_LEVEL_BASED",
    MEAL_BASED: "MEAL_BASED",
    COOKING_BASED: "COOKING_BASED",
    CUISINE_BASED: "CUISINE_BASED",
    AUDIENCE_BASED: "AUDIENCE_BASED",
    COURSE_BASED: "COURSE_BASED",     // Starter, Main Course
    BUSINESS_TAG_BASED: "BUSINESS_TAG_BASED" // Best Seller, New
  };