export const env = {
  WEB_BASE_URL: process.env.EXPO_PUBLIC_WEB_BASE_URL!,
  API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL!,

  FIREBASE_API_KEY: process.env.EXPO_PUBLIC_FIREBASE_API_KEY!,
  FIREBASE_PROJECT_ID: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID!,
  FIREBASE_APP_ID: process.env.EXPO_PUBLIC_FIREBASE_APP_ID!,

  //For media storage related
  APPWRITE_PROJECT_NAME: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_NAME!,
  APPWRITE_PROJECT_ID: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID!,
  APPWRITE_DATABASE_ID: process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID!,
  APPWRITE_STORAGE_BUCKET_ID:
    process.env.EXPO_PUBLIC_APPWRITE_STORAGE_BUCKET_ID!,
  APPWRITE_ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!,

  //firebase tables
  FIREBASE_USER_COLLECTION_ID: process.env.EXPO_PUBLIC_USERS_COLLECTION_NAME!,
  FIREBASE_SHOP_COLLECTION_ID: process.env.EXPO_PUBLIC_SHOPS_COLLECTION_NAME!,
  FIREBASE_MENU_CATEGORIES_COLLECTION_ID:
    process.env.EXPO_PUBLIC_MENU_CATEGORIES_COLLECTION_NAME!,
  FIREBASE_MENU_ITEMS_COLLECTION_ID:
    process.env.EXPO_PUBLIC_MENU_ITEMS_COLLECTION_NAME!,
  FIREBASE_ORDER_COLLECTION_ID: process.env.EXPO_PUBLIC_ORDERS_COLLECTION_NAME!,
  FIREBASE_ORDER_ITEMS_COLLECTION_ID:
    process.env.EXPO_PUBLIC_ORDER_ITEMS_COLLECTION_NAME!,
  FIREBASE_RATINGS_COLLECTION_ID:
    process.env.EXPO_PUBLIC_RATINGS_COLLECTION_NAME!,
  FIREBASE_FLOOR_ARRANGEMENTS_COLLECTION_ID:
    process.env.EXPO_PUBLIC_FLOOR_ARRANGEMENTS_COLLECTION_NAME!,
  FIREBASE_TABLE_ARRANGEMENTS_COLLECTION_ID:
    process.env.EXPO_PUBLIC_TABLE_ARRANGEMENTS_COLLECTION_NAME!,
  FIREBASE_ADDRESS_COLLECTION_ID:
    process.env.EXPO_PUBLIC_ADDRESSES_COLLECTION_NAME!,
};
